### PR TITLE
Make the process of image copying modular

### PR DESCRIPTION
**Pull request by dimara**
Hi,
These two patches make the process of image copying modular. This extends snf-image so it can copy images into disks that are neither local files nor kernel block devices, e.g., userspace-only disks.
Thanks,
dimara

### CODE REVIEW

**Comment by skalkoto** [comment]
Hello,

The idea of making the image copy modular is great, but I think you need to extend the implementation because it not complete. snf-image should be agnostic to the underline modules:

- Right now the get_src/dst_backend_type() functions decide which module to use. If I want to implement a new module, then I would have to alter those functions and altering existing code to extend something is not a good thing to do. The modules themselves should decide if they can handle an ID or not. snf-image should iterate over the list of available modules to find which module may handle this ID. You could add an extra argument to the modules API for this.

- Modules should be directories or at least add support for having directories as modules, so they may host multiple files. We could execute a module if it is a file or expect it to have an executable "run" file inside if it is a directory. The pithcat helper scripts for example, is part of the pithos src module. It should not be laying in the root directory of snf-image.

- Modules should have configuration files, probably under /etc/snf-image.d/backend which are directly sourced by them and not through common.sh. The modules are to decide the default values for their configuration variables. All the PITHOS_* and PITHCAT_* variables in defaults.in should be hosted in the configuration file of the pithos src module. The IMAGE_DIR variable should be part of the configuration file of the "file" src module. Since all the modules already source the common.sh that hosts /etc/default/snf-image, this is also backwards compatible.

- The null backend should be implemented in the null src module. I don't see why we should treat this as a special case and add an extra if block in create.

If we do all this then we could even split some modules into different binary packages. Someone could install snf-image without installing the pithos backend.

Also, concerning the build system, use separate Makefile.am files for backends, backends/src and backends/dst and use the SUBDIRS macro in each Makefile.am to include the subdirectories. If I want to add a new module I should be able to do this by only altering the Makefile.am of the current directory and not the root one. Check how this is done in snf-image-helper to include the  networking and tasks directories.

Finally, I think it is better if you prescribe the API of the modules with functions in common.sh. Right now you have the same "getopts" block replicated in every src module. If we want to support a new optional argument, we would have to change all the files. It's better if you implement this as function sourced by the modules.

P.S. I'll be out of reach for a few weeks starting from Tuesday.

**Comment by dimara** [comment]
Hi,

Thanks a lot for reviewing the patches. Most of what you say makes perfect
sense but.. needs someone to implement it :)

The purpose of this patch set was to support image copying to arbitrary
userspace-only disks. To simplify it I decided to make the whole copying
process modular. You are right in saying that the source backend is not
modular. We implement *only* 'file', 'http', and 'pithos'. If one wants to add
another backend one must change the code. Still it is easy to change
get_src_backent_type() to parse any prefix of the form *: and obtain the source
backend just like get_dst_backend_type() does.

If we implement the 'null' src module as a backend module, which probably exits
without dumping anything to stdout, there is a problem with the monitor
invocation, since the size of the image is unknown. I guess calling monitor
with -r 0 will do the trick.

I agree on having the API of the modules prescribed with functions in common.sh.

The /etc/snf-image.d/ change might not be that easy, if we want to support
backwards compatibitly (something we surely want).

The binary packages are distribution-specific. Splitting the binary package
should not affect this patch set as it is orthogonal to it..

So, I suggest to go for the first changes (change get_src_backend_type(), add
the 'null' source backend, prescribe the module API in common.sh), then
everything else can come on top in a separate patch set.

If you agree, I hope I find some time soon to implement the above and respin
this PR.

Thanks again,
dimara

**Comment by skalkoto** [comment]
Hello, I'm back

> The /etc/snf-image.d/ change might not be that easy, if we want to support backwards compatibitly (something we surely want).

This is not true! common.sh sources `/etc/default/snf-image` and every module sources `/etc/snf-image/src/<module_name>` (we should probably favour snf-image instead of snf-image.d i've suggested because it is already present). If a configuration option is in `/etc/default/snf-image` it will reach the module because the module itself sources `common.sh`. This is completely backward compatible. If a user updates snf-image and has some options in `/etc/default/snf-image` that are supposed to be under `/etc/snf-image/src/<module_name>` the thing will still work.

> If we implement the 'null' src module as a backend module, which probably exits
> without dumping anything to stdout, there is a problem with the monitor
> invocation, since the size of the image is unknown. I guess calling monitor
> with -r 0 will do the trick.

Yes, that's what I'm saying. If you use `-s` option in the null module it should return 0

> The binary packages are distribution-specific. Splitting the binary package
> should not affect this patch set as it is orthogonal to it..

This is not true concerning how this is implemented right now. If I split the pithos module into a different binary package and the user does not install it because he wants to use snf-image without synnefo, the `/etc/default/snf-image` file will still document pithos options that are not usable and the common.sh will still have pithos specific code. I don't see why the modules implemented by us should be treated in a different way than the user defined ones. All the module specific options should have default values inside the modules and not in common.sh and should be documented in order to overwrite them in module specific configuration files.

> I agree on having the API of the modules prescribed with functions in common.sh.

Yeah and common.sh should also prescribe the place where the configuration file of the module (official or unofficial) is hosted.

> So, I suggest to go for the first changes (change get_src_backend_type(), add
> the 'null' source backend, prescribe the module API in common.sh)

As I explained you in the previous post, the get_src_backend_type() function as it is implemented, it contains knowledge about which modules can handle an id, when this knowledge should be in the module side. We should find a way to let the user directly decide which module should handle the input (the <backend name>:<some custom identifier> thing you have), but we should also ask the modules in some priority order if they know how to handle an ID if the backend name is missing. We can discuss about how to make this in a backward compatible way.

> then everything else can come on top in a separate patch set.

Why implement this twice? Have a temporary implementation and then change it again inside the same development circle. If you don't have the time right now to implement it, then do a pull request when you have some time. 0.19 was just released and the 0.20 development circle has just started.

Also, take a look at the comments about the build system concerns and the SUBDIR macro.

Hope to hear from you soon,
Nikos

**Comment by skalkoto** [comment]
This functionality is implemented in develop

**Pull request closed without merging**
